const EmpData=[
    {
        "empno":"e001",
        "name":"Raju",
        "designation":"Admin",
        "salary":45000
    },
    {
        "empno":"e002",
        "name":"Mohan",
        "designation":"Engineer",
        "salary":95000
    },
    {
       "empno":"e003",
        "name":"Girish",
        "designation":"Doctor",
        "salary":80000
    },
    {
        "empno":"e004",
        "name":"Devesh",
        "designation":"Hr",
        "salary":70000
    },
    {
        "empno":"e005",
        "name":"Ashish",
        "designation":"Manager",
        "salary":156800
    },
    {
        "empno":"e006",
        "name":"Arun",
        "designation":"Service",
        "salary":16800
    },
    {
        "empno":"e007",
        "name":"Vikash",
        "designation":"Driver",
        "salary":20000
    }
]
export default EmpData;