const Student=[
        {
            "rollno":121,
            "name":"Raju",
            "city":"Bhopal",
            "fees":45000
        },
        {
            "rollno":122,
            "name":"Suraj",
            "city":"Indore",
            "fees":50000
        },
        {
            "rollno":123,
            "name":"Mohan",
            "city":"Gwalior",
            "fees":40000
        },
        {
            "rollno":124,
            "name":"Shyam",
            "city":"Dewas",
            "fees":42000
        },
        {
            "rollno":125,
            "name":"Ankit",
            "city":"Ujjain",
            "fees":55000
        },
        {
            "rollno":126,
            "name":"Akash",
            "city":"Jabalpur",
            "fees":52000
        },
        {
            "rollno":127,
            "name":"Dewansh",
            "city":"Sehore",
            "fees":48000
        },
        {
            "rollno":128,
            "name":"Sumit",
            "city":"Pune",
            "fees":60000
        }
]
export default Student;